server {
    listen 80;
    
    # Root directory where Vite outputs static files
    root /usr/share/nginx/html;
    index index.html index.htm;
    
    # Send all requests to index.html for React Router SPA
    location / {
        try_files $uri $uri/ /index.html;
    }
}
